apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-go-deployment
  labels:
    app: todo-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-go
  template:
    metadata:
      labels:
        app: todo-go
    spec:
      containers:
      - name: todo-go
        image: hikari3467/todo-go-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: todo-go-secret
              key: db-user
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: todo-go-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: todo-go-config
              key: db-port
        - name: SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: todo-go-config
              key: server-address
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: todo-go-config
              key: server-port
---
apiVersion: v1
kind: Service
metadata:
  name: todo-go-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: todo-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
